import { getCustomColumn, setCustomColumn } from '@/api/columns';

export const plantDefaultColumns = {
  // 固定显示的字段
  fixColums: [
    'row-select',
    'plantNameId',
    'op',
    'plantVideo',
    'sphInfo.sphName',
  ],
  // 默认显示的字段
  defaultColumns: [
    'estimatedWecoinAmount',
    'process',
    'cost',
    'productOrderCount',
    'productPlaceorderGmv',
    'lr',
    'roi',
    'yl_roi',
    'yjl',
    'airCost',
    'productClickCountPv',
    'exposureCount',
    'targetType',
    'wecoinBid',
    'duration',
    'click_rate',
    'qan_cost',
    'click_cost',
    'zh_cost',
    'cancelPlant',
    'groupInfo.groupName',
    'packageInfo.packageName',
    'noCostTime',
    'indemnifyVoucherStatus',
    'indemnifyVoucherAmount',
    'indemnifyVoucherIntoAmount',
    'indemnifyVoucherAmountRoi',
    'indemnifyTs',
    'voucherQuota',
    'updatedAt',
    'createdCancelTime',
    'startEndTime',
    'startCostTime',
    'hotNoCostTime',
    'newMemberDepName',
  ],
};
// getCustomColumn().then(({ data }) => {
//   console.log(JSON.parse(data.customColumnValue), 'ahkjdhkajhsd');
//   const userPlantColumns = JSON.parse(data.customColumnValue);
//   userPlantColumns.forEach((e: any) => {
//     if (!plantDefaultColumns.fixColums.includes(e.colKey)) {
//       console.log(123);
//       plantDefaultColumns.defaultColumns.push(e.colKey);
//     }
//   });
// });
export const plantColumnsGroup = [
  {
    label: '表格行配置',
    value: 'col',
    children: [
      {
        label: '投放数据',
        value: 'placementData',
        columns: [
          'estimatedWecoinAmount',
          'process',
          'cost',
          'airCost',
          'targetType',
          'wecoinBid',
          'duration',
          'voucherQuota',
          'cancelPlant',
          'groupInfo.groupName',
          'packageInfo.packageName',
          'updatedAt',
          'yjl',
          'createdCancelTime',
          'noCostTime',
          'startEndTime',
          'startCostTime',
          'newMemberDepName',
        ],
        check: [],
      },
      {
        label: '加热效果数据',
        value: 'hd',
        columns: [
          'productOrderCount',
          'productPlaceorderGmv',
          'lr',
          'roi',
          'yl_roi',
          'productClickCountPv',
          'exposureCount',
          'click_rate',
          'qan_cost',
          'click_cost',
          'zh_cost',
          'indemnifyVoucherStatus',
          'indemnifyVoucherAmount',
          // 'indemnifyVoucherIntoAmount',
          'indemnifyVoucherAmountRoi',
          'indemnifyTs',
          'hotNoCostTime',
        ],
        check: [],
      },
    ],
  },
];
export const plantColumnsData = [
  {
    colKey: 'row-select',
    type: 'multiple',
    width: 46,
    fixed: 'left',
    title: '行选择框',
  },
  {
    colKey: 'plantNameId',
    title: '计划名称/Id',
    width: '200',
    fixed: 'left',
    align: 'left',
  },
  {
    colKey: 'op',
    title: '状态/操作',
    width: '220',
    fixed: 'left',

    align: 'center',
  },

  {
    colKey: 'plantVideo',
    title: '被投视频',
    width: '450',
    align: 'left',
  },

  {
    colKey: 'sphInfo.sphName',
    title: '投放号',
    width: '150',
    align: 'center',
  },
  {
    colKey: 'estimatedWecoinAmount',
    title: '投放金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },

  {
    colKey: 'process',
    title: '消耗比例',
    width: '170',
    align: 'center',
  },
  {
    colKey: 'cost',
    title: '消耗金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productOrderCount',
    title: '订单数',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productPlaceorderGmv',
    title: '营业额',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'lr',
    title: '利润',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'roi',
    title: 'ROI',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yl_roi',
    title: '佣金ROI',
    width: '125',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yjl',
    title: '佣金率',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'airCost',
    title: '空耗值',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productClickCountPv',
    title: '商品点击',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'exposureCount',
    title: '浏览',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'targetType',
    title: '投放目标',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'wecoinBid',
    title: '出价',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'duration',
    title: '投放时长',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_rate',
    title: '点击率',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'qan_cost',
    title: '千展成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_cost',
    title: '点击成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'zh_cost',
    title: '转化成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'cancelPlant',
    title: '自动关停',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'groupInfo.groupName',
    title: '所属分组',
    width: '140',
    align: 'center',
  },
  {
    colKey: 'packageInfo.packageName',
    title: '所属计划包',
    width: '180',
    align: 'center',
  },
  {
    colKey: 'noCostTime',
    title: '无消耗时长',
    width: '200',
    align: 'center',
    sorter: true,
    sortType: 'all',
  },
  {
    colKey: 'indemnifyVoucherStatus',
    title: '补贴状态',
    width: '120',
    align: 'center',
  },
  // {
  //   colKey: 'indemnifyVoucherAmount',
  //   title: '补贴金额',
  //   width: '120',
  //   align: 'center',
  // },
  // {
  //   colKey: 'indemnifyVoucherIntoAmount',
  //   title: '已补贴金额',
  //   width: '120',
  //   align: 'center',
  // },

  {
    colKey: 'indemnifyVoucherAmount',
    title: '补贴金额',
    width: '120',
    align: 'center',
  },
  /* 暂时都不上 */
  // {
  //   colKey: 'indemnifyVoucherIntoAmount',
  //   title: '已补贴金额',
  //   width: '120',
  //   align: 'center',
  // },
  {
    colKey: 'indemnifyVoucherAmountRoi',
    title: '补贴ROI',
    width: '120',
    align: 'center',
  },

  {
    colKey: 'indemnifyTs',
    title: '补贴时间',
    width: '200',
    align: 'center',
  },
  {
    colKey: 'voucherQuota',
    title: '优惠券抵扣',
    width: '120',
    align: 'center',
  },
  {
    colKey: 'updatedAt',
    title: '更新时间',
    width: '200',
    align: 'center',
  },

  {
    colKey: 'createdCancelTime',
    title: '创建/关闭时间',
    width: '240',
  },
  {
    colKey: 'startEndTime',
    title: '加热开始/结束时间',
    width: '240',
  },
  {
    colKey: 'startCostTime',
    title: '开始消耗时间',
    width: '240',
    align: 'center',
  },
  {
    colKey: 'hotNoCostTime',
    title: '加热未消耗时长',
    width: '140',
    align: 'center',
  },
  {
    colKey: 'newMemberDepName',
    title: '所属部门',
    width: '140',
    align: 'center',
  },
];
export const plantColumnsDataS = [
  {
    colKey: 'row-select',
    type: 'multiple',
    width: 46,
    fixed: 'left',
    title: '行选择框',
  },
  {
    colKey: 'plantNameId',
    title: '计划名称/Id',
    width: '200',
    fixed: 'left',
    align: 'left',
  },
  {
    colKey: 'op',
    title: '状态/操作',
    width: '220',
    fixed: 'left',

    align: 'center',
  },

  {
    colKey: 'plantVideo',
    title: '被投视频',
    width: '450',
    align: 'left',
  },

  {
    colKey: 'sphInfo.sphName',
    title: '投放号',
    width: '150',
    align: 'center',
  },
  {
    colKey: 'estimatedWecoinAmount',
    title: '投放金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },

  {
    colKey: 'process',
    title: '消耗比例',
    width: '170',
    align: 'center',
  },
  {
    colKey: 'cost',
    title: '消耗金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productOrderCount',
    title: '订单数',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productPlaceorderGmv',
    title: '营业额',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'lr',
    title: '利润',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'roi',
    title: 'ROI',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yl_roi',
    title: '佣金ROI',
    width: '125',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yjl',
    title: '佣金率',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'airCost',
    title: '空耗值',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productClickCountPv',
    title: '商品点击',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'exposureCount',
    title: '浏览',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'targetType',
    title: '投放目标',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'wecoinBid',
    title: '出价',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'duration',
    title: '投放时长',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_rate',
    title: '点击率',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'qan_cost',
    title: '千展成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_cost',
    title: '点击成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'zh_cost',
    title: '转化成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'cancelPlant',
    title: '自动关停',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'groupInfo.groupName',
    title: '所属分组',
    width: '140',
    align: 'center',
  },
  {
    colKey: 'packageInfo.packageName',
    title: '所属计划包',
    width: '180',
    align: 'center',
  },
  {
    colKey: 'noCostTime',
    title: '无消耗时长',
    width: '200',
    align: 'center',
    sorter: true,
    sortType: 'all',
  },
  {
    colKey: 'indemnifyVoucherStatus',
    title: '补贴状态',
    width: '120',
    align: 'center',
  },
  // {
  //   colKey: 'indemnifyVoucherAmount',
  //   title: '补贴金额',
  //   width: '120',
  //   align: 'center',
  // },
  // {
  //   colKey: 'indemnifyVoucherIntoAmount',
  //   title: '已补贴金额',
  //   width: '120',
  //   align: 'center',
  // },

  {
    colKey: 'indemnifyVoucherAmount',
    title: '补贴金额',
    width: '120',
    align: 'center',
  },
  /* 暂时都不上 */
  // {
  //   colKey: 'indemnifyVoucherIntoAmount',
  //   title: '已补贴金额',
  //   width: '120',
  //   align: 'center',
  // },
  {
    colKey: 'indemnifyVoucherAmountRoi',
    title: '补贴ROI',
    width: '120',
    align: 'center',
  },

  {
    colKey: 'indemnifyTs',
    title: '补贴时间',
    width: '200',
    align: 'center',
  },
  {
    colKey: 'voucherQuota',
    title: '优惠券抵扣',
    width: '120',
    align: 'center',
  },
  {
    colKey: 'updatedAt',
    title: '更新时间',
    width: '200',
    align: 'center',
  },

  {
    colKey: 'createdCancelTime',
    title: '创建/关闭时间',
    width: '240',
  },
  {
    colKey: 'startEndTime',
    title: '加热开始/结束时间',
    width: '240',
  },
  {
    colKey: 'startCostTime',
    title: '开始消耗时间',
    width: '240',
    align: 'center',
  },
  {
    colKey: 'hotNoCostTime',
    title: '加热未消耗时长',
    width: '140',
    align: 'center',
  },
  {
    colKey: 'newMemberDepName',
    title: '所属部门',
    width: '140',
    align: 'center',
  },
];
// export const plantColumnsDataS = [
//   {
//     colKey: 'row-select',
//     type: 'multiple',
//     width: 46,
//     fixed: 'left',
//     title: '行选择框',
//   },
//   {
//     colKey: 'plantNameId',
//     title: '计划名称/Id',
//     width: '200',
//     fixed: 'left',
//     align: 'left',
//   },
//   {
//     colKey: 'op',
//     title: '状态/操作',
//     width: '220',
//     fixed: 'left',

//     align: 'center',
//   },

//   {
//     colKey: 'plantVideo',
//     title: '被投视频',
//     width: '450',
//     align: 'left',
//   },

//   {
//     colKey: 'sphInfo.sphName',
//     title: '投放号',
//     width: '150',
//     align: 'center',
//   },
//   {
//     colKey: 'estimatedWecoinAmount',
//     title: '投放金额',
//     width: '120',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },

//   {
//     colKey: 'process',
//     title: '消耗比例',
//     width: '170',
//     align: 'center',
//   },
//   {
//     colKey: 'cost',
//     title: '消耗金额',
//     width: '120',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'productOrderCount',
//     title: '订单数',
//     width: '100',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'productPlaceorderGmv',
//     title: '营业额',
//     width: '100',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'lr',
//     title: '利润',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'roi',
//     title: 'ROI',
//     width: '100',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'yl_roi',
//     title: '佣金ROI',
//     width: '125',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'yjl',
//     title: '佣金率',
//     width: '100',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'airCost',
//     title: '空耗值',
//     width: '120',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'productClickCountPv',
//     title: '商品点击',
//     width: '120',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'exposureCount',
//     title: '浏览',
//     width: '100',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'targetType',
//     title: '投放目标',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'wecoinBid',
//     title: '出价',
//     width: '100',
//     align: 'center',
//     sortType: 'all',
//     sorter: true,
//   },
//   {
//     colKey: 'duration',
//     title: '投放时长',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'click_rate',
//     title: '点击率',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'qan_cost',
//     title: '千展成本',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'click_cost',
//     title: '点击成本',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'zh_cost',
//     title: '转化成本',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'cancelPlant',
//     title: '自动关停',
//     width: '100',
//     align: 'center',
//   },
//   {
//     colKey: 'groupInfo.groupName',
//     title: '所属分组',
//     width: '140',
//     align: 'center',
//   },
//   {
//     colKey: 'packageInfo.packageName',
//     title: '所属计划包',
//     width: '180',
//     align: 'center',
//   },
//   {
//     colKey: 'noCostTime',
//     title: '无消耗时长',
//     width: '200',
//     align: 'center',
//     sorter: true,
//     sortType: 'all',
//   },
//   {
//     colKey: 'indemnifyVoucherStatus',
//     title: '补贴状态',
//     width: '120',
//     align: 'center',
//   },
//   {
//     colKey: 'indemnifyVoucherAmount',
//     title: '预计补贴金额',
//     width: '120',
//     align: 'center',
//   },
//   {
//     colKey: 'indemnifyVoucherIntoAmount',
//     title: '已补贴金额',
//     width: '120',
//     align: 'center',
//   },
//   {
//     colKey: 'indemnifyVoucherAmountRoi',
//     title: '预计补贴ROI',
//     width: '120',
//     align: 'center',
//   },
//   {
//     colKey: 'indemnifyTs',
//     title: '补贴时间',
//     width: '200',
//     align: 'center',
//   },
//   {
//     colKey: 'voucherQuota',
//     title: '优惠券抵扣',
//     width: '120',
//     align: 'center',
//   },
//   {
//     colKey: 'updatedAt',
//     title: '更新时间',
//     width: '200',
//     align: 'center',
//   },

//   {
//     colKey: 'createdCancelTime',
//     title: '创建/关闭时间',
//     width: '240',
//   },
//   {
//     colKey: 'startEndTime',
//     title: '加热开始/结束时间',
//     width: '240',
//   },
//   {
//     colKey: 'startCostTime',
//     title: '开始消耗时间',
//     width: '240',
//     align: 'center',
//   },
//   {
//     colKey: 'newMemberDepName',
//     title: '所属部门',
//     width: '140',
//     align: 'center',
//   },
// ];
