export const liveplantDefaultColumns = {
  // 固定显示的字段
  fixColums: [
    'row-select',
    'plantNameId',
    'op',
    'plantVideo',
    'sphInfo.sphName',
  ],
  // 默认显示的字段
  defaultColumns: [
    'estimatedWecoinAmount',
    'process',

    'cost',
    'productOrderCount',
    'productPlaceorderGmv',
    'lr',
    'roi',
    'yl_roi',
    'yjl',
    'airCost',
    'productClickCountUv',
    'exposureCount',
    'targetType',
    'wecoinBid',
    'duration',
    'click_rate',
    'qan_cost',
    'click_cost',
    'zh_cost',
    'cancelPlant',
    'packageInfo.packageName',
    'noCostTime',
    'updatedAt',
    'createdCancelTime',
    'startEndTime',
    'startCostTime',
    'newMemberDepName',
  ],
};
export const plantColumnsData = [
  {
    colKey: 'row-select',
    type: 'multiple',
    width: 46,
    fixed: 'left',
    title: '行选择框',
  },
  {
    colKey: 'plantNameId',
    title: '计划名称/Id',
    width: '200',
    fixed: 'left',
    align: 'left',
  },
  {
    colKey: 'op',
    title: '状态/操作',
    width: '220',
    fixed: 'left',

    align: 'center',
  },
  {
    colKey: 'plantVideo',
    title: '被投信息',
    width: '250',
    align: 'left',
  },

  {
    colKey: 'sphInfo.sphName',
    title: '投放号',
    width: '150',
    align: 'center',
  },
  {
    colKey: 'estimatedWecoinAmount',
    title: '投放金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'process',
    title: '消耗比例',
    width: '170',
    align: 'center',
  },
  {
    colKey: 'cost',
    title: '消耗金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productOrderCount',
    title: '订单数',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productPlaceorderGmv',
    title: '营业额',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'lr',
    title: '利润',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'roi',
    title: 'ROI',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yl_roi',
    title: '佣金ROI',
    width: '125',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yjl',
    title: '佣金率',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'airCost',
    title: '空耗值',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productClickCountUv',
    title: '商品点击',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'exposureCount',
    title: '浏览',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'targetType',
    title: '投放目标',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'wecoinBid',
    title: '出价',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'duration',
    title: '投放时长',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_rate',
    title: '点击率',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'qan_cost',
    title: '千展成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_cost',
    title: '点击成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'zh_cost',
    title: '转化成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'cancelPlant',
    title: '自动关停',
    width: '100',
    align: 'center',
  },

  {
    colKey: 'packageInfo.packageName',
    title: '所属计划包',
    width: '180',
    align: 'center',
  },
  {
    colKey: 'noCostTime',
    title: '无消耗时长',
    width: '200',
    align: 'center',
    sorter: true,
    sortType: 'all',
  },
  {
    colKey: 'updatedAt',
    title: '更新时间',
    width: '200',
    align: 'center',
  },
  {
    colKey: 'createdCancelTime',
    title: '创建/关闭时间',
    width: '240',
  },
  {
    colKey: 'startEndTime',
    title: '加热开始/结束时间',
    width: '240',
  },
  {
    colKey: 'startCostTime',
    title: '开始消耗时间',
    width: '240',
    align: 'center',
  },
  {
    colKey: 'newMemberDepName',
    title: '所属部门',
    width: '140',
    align: 'center',
  },
];

export const liveplantColumnsGroup = [
  {
    label: '表格行配置',
    value: 'col',
    children: [
      {
        label: '投放数据',
        value: 'liveplacementData',
        columns: [
          'estimatedWecoinAmount',
          'process',
          'cost',
          'airCost',
          'targetType',
          'wecoinBid',
          'duration',
          'cancelPlant',
          'packageInfo.packageName',
          'updatedAt',
          'yjl',
          'createdCancelTime',
          'noCostTime',
          'startEndTime',
          'startCostTime',
          'newMemberDepName',
        ],
        check: [],
      },
      {
        label: '加热效果数据',
        value: 'livehd',
        columns: [
          'productOrderCount',
          'productPlaceorderGmv',
          'lr',
          'roi',
          'yl_roi',
          'productClickCountUv',
          'exposureCount',
          'click_rate',
          'qan_cost',
          'click_cost',
          'zh_cost',
        ],
        check: [],
      },
    ],
  },
];
export const liveplantColumnsData = [
  {
    colKey: 'row-select',
    type: 'multiple',
    width: 46,
    fixed: 'left',
    title: '行选择框',
  },
  {
    colKey: 'plantNameId',
    title: '计划名称/Id',
    width: '200',
    fixed: 'left',
    align: 'left',
  },
  {
    colKey: 'op',
    title: '状态/操作',
    width: '220',
    fixed: 'left',

    align: 'center',
  },
  {
    colKey: 'plantVideo',
    title: '被投信息',
    width: '250',
    align: 'left',
  },

  {
    colKey: 'sphInfo.sphName',
    title: '投放号',
    width: '150',
    align: 'center',
  },
  {
    colKey: 'estimatedWecoinAmount',
    title: '投放金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'process',
    title: '消耗比例',
    width: '170',
    align: 'center',
  },
  {
    colKey: 'cost',
    title: '消耗金额',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productOrderCount',
    title: '订单数',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productPlaceorderGmv',
    title: '营业额',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'lr',
    title: '利润',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'roi',
    title: 'ROI',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yl_roi',
    title: '佣金ROI',
    width: '125',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'yjl',
    title: '佣金率',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'airCost',
    title: '空耗值',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'productClickCountUv',
    title: '商品点击',
    width: '120',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'exposureCount',
    title: '浏览',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'targetType',
    title: '投放目标',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'wecoinBid',
    title: '出价',
    width: '100',
    align: 'center',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'duration',
    title: '投放时长',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_rate',
    title: '点击率',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'qan_cost',
    title: '千展成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'click_cost',
    title: '点击成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'zh_cost',
    title: '转化成本',
    width: '100',
    align: 'center',
  },
  {
    colKey: 'cancelPlant',
    title: '自动关停',
    width: '100',
    align: 'center',
  },

  {
    colKey: 'packageInfo.packageName',
    title: '所属计划包',
    width: '180',
    align: 'center',
  },
  {
    colKey: 'noCostTime',
    title: '无消耗时长',
    width: '200',
    align: 'center',
    sorter: true,
    sortType: 'all',
  },
  {
    colKey: 'updatedAt',
    title: '更新时间',
    width: '200',
    align: 'center',
  },
  {
    colKey: 'createdCancelTime',
    title: '创建/关闭时间',
    width: '240',
  },
  {
    colKey: 'startEndTime',
    title: '加热开始/结束时间',
    width: '240',
  },
  {
    colKey: 'startCostTime',
    title: '开始消耗时间',
    width: '240',
    align: 'center',
  },
  {
    colKey: 'newMemberDepName',
    title: '所属部门',
    width: '140',
    align: 'center',
  },
];
